server:
  http_listen_port: 9091

prometheus:
  wal_directory: /var/lib/grafana-agent/wal
  global:
    scrape_interval: 15s

integrations:
  docker:
    endpoint: unix:///var/run/docker.sock

  jmx:
    custom_rules:
      - pattern: ".*"
        name: jmx_exporter
        labels:
          job: jmx
          instance: tomcat

